import type { Treatment, Dentist, BusinessHour } from '../types/index.ts';

export const FALLBACK_TREATMENTS: Treatment[] = [
  {
    id: 1,
    name: 'Limpieza Dental',
    slug: 'limpieza-dental',
    shortDescription: 'Profilaxis completa para eliminar sarro y placa bacteriana.',
    description: 'Limpieza profesional profunda que previene enfermedades periodontales y mantiene tu sonrisa sana.',
    benefits: ['Elimina sarro y placa', 'Previene gingivitis', 'Pulido dental incluido', 'Aplicación de flúor'],
    durationMinutes: 45,
    price: 45000,
    imageUrl: '/images/tratamiento-limpieza.jpg',
    isFeatured: true,
    sortOrder: 1,
  },
  {
    id: 2,
    name: 'Blanqueamiento Dental',
    slug: 'blanqueamiento-dental',
    shortDescription: 'Aclara el tono de tus dientes de forma segura y efectiva.',
    description: 'Tratamiento estético profesional que devuelve el brillo natural a tu sonrisa en una sola sesión.',
    benefits: ['Resultados inmediatos', 'Seguro para el esmalte', 'Sin sensibilidad', 'Duración hasta 2 años'],
    durationMinutes: 90,
    price: 180000,
    imageUrl: '/images/tratamiento-blanqueamiento.jpg',
    isFeatured: true,
    sortOrder: 2,
  },
  {
    id: 3,
    name: 'Implantes Dentales',
    slug: 'implantes-dentales',
    shortDescription: 'Reemplaza piezas ausentes con implantes de titanio de última generación.',
    description: 'Solución permanente para dientes perdidos que recupera función masticatoria y estética.',
    benefits: ['Titanio grado médico', 'Garantía de por vida', 'Cirugía mínimamente invasiva', 'Recuperación rápida'],
    durationMinutes: 120,
    price: 850000,
    imageUrl: '/images/tratamiento-implantes.jpg',
    isFeatured: true,
    sortOrder: 3,
  },
  {
    id: 4,
    name: 'Ortodoncia',
    slug: 'ortodoncia',
    shortDescription: 'Alinea tus dientes con brackets o alineadores transparentes.',
    description: 'Corrección de maloclusiones y apiñamiento dental con tecnología de vanguardia.',
    benefits: ['Alineadores invisibles', 'Brackets estéticos', 'Planificación digital 3D', 'Controles mensuales'],
    durationMinutes: 60,
    price: 250000,
    imageUrl: '/images/tratamiento-ortodoncia.jpg',
    isFeatured: false,
    sortOrder: 4,
  },
  {
    id: 5,
    name: 'Carillas Dentales',
    slug: 'carillas-dentales',
    shortDescription: 'Láminas ultrafinas de porcelana para una sonrisa perfecta.',
    description: 'Transformación estética inmediata que corrige forma, color y tamaño de los dientes.',
    benefits: ['Porcelana de alta resistencia', 'Mínimo desgaste dental', 'Color natural personalizado', 'Duración 15+ años'],
    durationMinutes: 120,
    price: 320000,
    imageUrl: '/images/tratamiento-carillas.jpg',
    isFeatured: false,
    sortOrder: 5,
  },
  {
    id: 6,
    name: 'Odontopediatría',
    slug: 'odontopediatria',
    shortDescription: 'Cuidado dental especializado para niños y adolescentes.',
    description: 'Atención pediátrica integral con enfoque preventivo y manejo de conducta.',
    benefits: ['Ambiente amigable', 'Prevención de caries', 'Sellantes de fosas', 'Educación en higiene'],
    durationMinutes: 30,
    price: 35000,
    imageUrl: '/images/tratamiento-odontopediatria.jpg',
    isFeatured: false,
    sortOrder: 6,
  },
];

const emptyBusinessHours: BusinessHour[] = [];

export const FALLBACK_DENTISTS: Dentist[] = [
  {
    id: 1,
    name: 'Dra. Valentina Rojas',
    role: 'Cirujana Dentista',
    specialty: 'Implantes dentales y Cirugía bucal',
    description: 'Especialista en implantes dentales y cirugía oral con más de 10 años de experiencia.',
    experienceYears: 12,
    imageUrl: '/avatar-female1.jpg',
    isActive: true,
    businessHours: emptyBusinessHours,
  },
  {
    id: 2,
    name: 'Dr. Sebastián Fuentes',
    role: 'Ortodoncista',
    specialty: 'Ortodoncia y Alineadores invisibles',
    description: 'Experto en ortodoncia moderna y alineadores transparentes.',
    experienceYears: 8,
    imageUrl: '/avatar-male1.jpg',
    isActive: true,
    businessHours: emptyBusinessHours,
  },
  {
    id: 3,
    name: 'Dra. Camila Torres',
    role: 'Odontóloga Restauradora',
    specialty: 'Odontología restauradora y estética',
    description: 'Especialista en rehabilitación oral y estética dental avanzada.',
    experienceYears: 10,
    imageUrl: '/avatar-female2.jpg',
    isActive: true,
    businessHours: emptyBusinessHours,
  },
  {
    id: 4,
    name: 'Dr. Andrés Muñoz',
    role: 'Odontopediatra y Endodoncista',
    specialty: 'Odontopediatría y Endodoncia',
    description: 'Experto en atención dental infantil y tratamientos de conducto.',
    experienceYears: 7,
    imageUrl: '/avatar-male2.jpg',
    isActive: true,
    businessHours: emptyBusinessHours,
  },
];